version: '3.7'

networks:
  web:
      external: true
  internal:
      external: false
      driver: bridge   

services:
  caddy:
      image: caddy:2-alpine
      restart: unless-stopped
      ports:
              - "80:80"
              - "443:443"
      volumes:
              - caddy/Caddyfile:/etc/caddy/Caddyfile
              - caddy/data:/data # Optional
              - caddy/config:/config # Optional
      networks:
              - web
              - internal
  frontend:
    container_name: frontend
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    image: pocland-frontend:latest
    build:
      context: ./frontend
      dockerfile: Prod.dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
    command: npm start
    restart: always

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
        - $DB_PORT:$DB_PORT
    volumes:
        - pocland-db:/var/lib/mysql
        - ./database/query:/docker-entrypoint-initdb.d

  server:
    container_name: server
    image: pocland-server:latest
    build:
      context: ./server
      dockerfile: Prod.dockerfile
    env_file:
      - .env
    environment:
      PORT: $SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    restart: always

volumes:
    pocland-db:
